{
	"version": 1654713958,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/ufo-sheet0.png",
		"images/tela_menu-sheet0.png",
		"images/opcçõesmenu.png",
		"images/ufo_menu-sheet0.png",
		"images/tela_how-sheet0.png",
		"images/tela_creditos-sheet0.png",
		"images/fundogame-sheet0.png",
		"images/sprite-sheet0.png",
		"images/vaca-sheet0.png",
		"images/vaca-sheet1.png",
		"images/vaca-sheet2.png",
		"images/vacabrancapintadafundo-sheet0.png",
		"images/barreira-sheet0.png",
		"images/telagameover-sheet0.png",
		"images/fontecreditos.png",
		"images/powerup_dinheiro-sheet0.png",
		"images/powerup_escudo-sheet0.png",
		"images/antiufo-sheet0.png",
		"images/disparo-sheet0.png",
		"images/disparo-sheet1.png",
		"images/powerup_desacelerar-sheet0.png",
		"images/ufo2-sheet0.png",
		"media/snd_death.m4a",
		"media/snd_death.ogg",
		"media/snd_shot.m4a",
		"media/snd_shot.ogg",
		"media/moo.m4a",
		"media/moo.ogg",
		"media/moo2.m4a",
		"media/moo2.ogg",
		"media/pickupcoin.m4a",
		"media/pickupcoin.ogg",
		"media/powerup.m4a",
		"media/sound.ogg",
		"media/vaca.m4a",
		"media/vaca.ogg",
		"media/intro musica gameover.m4a",
		"media/intro musica gameover.ogg",
		"media/intro musica partida.m4a",
		"media/intro musica partida.ogg",
		"media/musica gam.m4a",
		"media/musica gam.ogg",
		"media/musica game partida.m4a",
		"media/musica game partida.ogg",
		"media/musica gameover.m4a",
		"media/musica gameover.ogg",
		"media/musica partida.m4a",
		"media/musica partida.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}